- easypost/__init__.py
When creating an address with fields that contain extended latin characters, I was getting a UnicodeEncodeError at this spot.  This fix correctly encodes unicode text to UTF-8.
> Fix encoding errors with non-ASCII characters.

- easypost/__init__.py
If the easypost_id is passed as a string and that string includes "id" as a substring, then the if will return True but the string will raise a TypeError when accessed with the nonnumeric index of "id".
This PR attempts to account for that without reverting all the way back to catching a naked exception.
> handle attempts to retrieve a resource with an easypost_id string containing 'id' substring

- easypost/__init__.py
Tested in 2.7 and 3.5, seems to work. 3.5 warns about ssl sockets not being closed due to pooling. We really need to rewrite/refactor this(so we can properly close the pool when the "Requestor" is destroyed, but also other reasons).
> Use requests session

- MANIFEST.in
- README.md
- easypost/__init__.py
- tests/test_report.py
- tests/test_webhook.py
Inspired by python3 test failures before @Roguelazer modernized them. The order of 'all()' changes.
> Dicts iterate differently on python 2 vs. 3. Let's sort.

- easypost/__init__.py
This change adds support for using a custom timeout. It can be set similar to how `api_key` is set.
```
import easypost
easypost.api_key = '<YOUR API KEY>'
easypost.timeout = 30
```
> Support using a custom timeout for requests

- .travis.yml
> attempt to add python 3.7 and pypy3.5 to the build matrix

- setup.py
The 'setup.py' didn't separate the install_requires list arguments with a comma. I believe that is what was preventing the 'six' library from being installed by pip
> fix install_requires typo that prevented 'six' from being installed

- .gitignore
- tests/test_batch.py
- tests/test_pickup.py
- tests/test_report.py
It's been some time since unit tests were run and some items have changed making a few fail. The following changes are fixes to bring unit tests into the current state of the EasyPost API and carrier requirements so unit tests will pass once again.
> Fix unit tests

- easypost/__init__.py
We've had multiple people test and confirm that the Python client library wraps params for reports incorrectly which leads to users not being able to create reports via the client library and have them show up on their Dashboard. With this fix in place, reports will create properly with the correct parameter wrapping and they show up on the Dashboard.
Let me know if I need to do a version bump etc for this or if that's something handled by someone else.
> Fixing the create reports params wrapping issue

- pytest.ini
- requirements-tests.txt
- tests/test_batch.py
- tests/test_shipment.py
Fixes an issue with 1¢ rates (see https://www.easypost.com/pricing for current pricing).
Fixes an issue with rerating. Amusingly, while we didn't have any backend tests on the bizarro write-on-GET `/rates` behavior, we _did_ test it in this client library. What a weird world.
> fix tests and update pytest to latest 2.x-compatible version

- easypost/__init__.py
Our docs say to use POST for refunds but the CL uses GET. It works as there are not params to pass but it should probably match for clarity and uniformity.
Closes #105
> Swap GET to POST on Refund method

- easypost/__init__.py
- tests/cassettes/test_smartrate.yaml
- tests/test_shipment.py
Adds the new `/smartrate` endpoint/method on the `Shipment` object.
Simply call `get_smartrates` on the shipment object and you'll be returned a list of smartrates like so:
```json
{
"result": [
{
"carrier": "USPS",
"carrier_account_id": "ca_123...",
"created_at": "2021-05-04T21:15:59Z",
"currency": "USD",
"delivery_date": null,
"delivery_date_guaranteed": true,
"delivery_days": null,
"est_delivery_days": null,
"id": "rate_123...",
"list_currency": null,
"list_rate": null,
"mode": "test",
"object": "Rate",
"rate": 0.01,
"retail_currency": null,
"retail_rate": null,
"service": "First",
"shipment_id": "shp_123",
"time_in_transit": {
"percentile_50": 2,
"percentile_75": 3,
"percentile_85": 4,
"percentile_90": 4,
"percentile_95": 4,
"percentile_97": 4,
"percentile_99": 4
},
"updated_at": …
```
> feat(smartrate): adds smartrate functionality

- CHANGELOG.md
- setup.py
Version bump from v5.0.0 to v5.1.0 for new SmartRate functionality.
Will need help cutting a new release on PyPi. Would be cool to have auto-releasing via GitHub Actions when a new tag is created.
> chore: bump to v5.1.0 for SmartRate

- easypost/__init__.py
- tests/cassettes/test_smartrate.yaml
- tests/test_shipment.py
Fixes Smartrate by not appending the results to a Shipment object anymore.
Previously we were appending the `results` list from Smartrates to the Shipment object by refreshing the record. We don't want to be doing this - instead we want to simply return the smartrate results without the accompanying shipment data.
[This was caught](https://github.com/EasyPost/easypost-ruby/pull/117#discussion_r632764921) in the Ruby library and others but I failed to see it here.
I was able to end-to-end test this to ensure it only returned the Smartrate `results` array and not the `Shipment` object in addition.
> fix: stops appending smartrates to Shipment object

- easypost/__init__.py
- tests/cassettes/test_rerate.yaml
- tests/cassettes/test_shipment_creation.yaml
- tests/test_shipment.py
Starting soon in the future,`get_rates()` will always be read-only (as you would expect from a GET), and re-rating will be triggered through the new `regenerate_rates()` function. This adds the new function. No change has occurred to `get_rates()` yet.
> add new regenerate_rates method corresponding to the new rerate api

- easypost/__init__.py
- tests/cassettes/test_smartrate.yaml
- tests/test_shipment.py
To provide a more idiomatic experience using SmartRate, we've decided to strip out the `result` key from the response of SmartRate. If for whatever reason we can't get smartrates, we'll fallback to an empty array.
> fix: strips the result key from smartrate

- CHANGELOG.md
- README.md
- easypost/version.py
- setup.py
Bumps version to 5.1.2 for Smartrate fix (patch).
Not sure the best version bump here as we intended for Smartrate to not include the `result` key but it is a breaking change. Open to thoughts.
> chore: bump version for smartrate correction

- CHANGELOG.md
- easypost/__init__.py
This endpoint was introduced as an experiment in 2015 and never documented. It has no users and is being removed.
> remove 2015-vintage experimental "all_updated" action on trackers

- CHANGELOG.md
- easypost/__init__.py
We haven't used the `contact@easypost.com` email for some time for support inquiries, correct it to `support@easypost.com`.
> fix: corrects support email in error messages

- easypost/__init__.py
- tests/cassettes/test_address_creation_with_verify_bool.yaml
- tests/test_address.py
allows users to just pass `True` for verify and verify_strict instead of having to pass `[True]`. Also properly quotes in case a user accidentally passes something icky.
as always, I am a firm believer that functions should be functions, not classmethods
> clean up address verify property and some miscellaneous request logic

- tests/conftest.py
- tests/test_shipment.py
Some small tweaks are needed to prevent non-test-error failures when testing with the appengine sdk instead of requests lib.
closes #140 
With the google cloud SDK installed and PYTHONPATH pointing at `google-cloud-sdk/platform/google_appengine/`, tests fail abruptly without these changes and pass with them.
> Make unit tests run in a local appengine environment

- CHANGELOG.md
- easypost/__init__.py
Removes `_max_timeout` and instead uses a flat 60 second timeout for requests to match other client libraries.
> Removes `_max_timeout` and instead uses a flat 60 second timeout for requests

- CHANGELOG.md
- easypost/__init__.py
Adds the Python version to user-agent header.
Tested via the repl:
```bash
jhammond@easypost $ python3
Python 3.9.9 (main, Nov 21 2021, 03:23:42) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.python_version()
'3.9.9'
```
> feat: adds the Python version to user-agent header

- easypost/__init__.py
- tests/cassettes/test_tracker_create_list.yaml
- tests/test_tracker.py
Improve the **create_list** for our Python library Tracker class.
Currently, the user must define a map that is named "trackers". An error can be thrown if the user mistypes the word. Instead, in our create_list method, we are going to create another map that has "trackers" as the key and user input as the value.
Add another map in **create_list** method and define "trackers" as the key and store user input as the value.
Re-record the cassette and pass the unit test.
> improve create_list for tracker class.

- CHANGELOG.md
- easypost/__init__.py
- tests/test_shipment.py
Rather than calling `shipment.get_rates()`, use `shipment.rates`. To refresh rates, call `shipment.regenerate_rates()`
> Remove old `get_rates()` method on `Shipment`

- easypost/address.py
- easypost/batch.py
- easypost/carrier_account.py
- easypost/event.py
- easypost/report.py
- easypost/resource.py
- easypost/scanform.py
- easypost/user.py
There is no need to wrap `convert_to_easypost_object` in `util` as it provides no value and is confusing; instead, we should just import the function directly.
> fix: import util.convert_to_easypost_object directly

- easypost/requestor.py
This should be backported to all previous series (3.x, 4.x, 5.x, etc).
> collect python_implementation in easypost-python user-agent

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- easypost/address.py
- easypost/batch.py
- easypost/carrier_account.py
- easypost/easypost_object.py
- easypost/error.py
- easypost/event.py
- easypost/order.py
- easypost/pickup.py
- easypost/report.py
- easypost/requestor.py
- easypost/resource.py
- easypost/scanform.py
- easypost/shipment.py
- easypost/tracker.py
- easypost/user.py
- easypost/version.py
- easypost/webhook.py
- setup.py
- tests/cassettes/test_report_all.yaml
- tests/cassettes/test_report_retrieve_tracker_report.yaml
- tests/conftest.py
- tests/test_refund.py
By providing type hints, we can make it our code semi-self-documenting, and a lot friendlier to those using IDEs (or really anyone). Users will now know what type each parameter of a function is supposed to be, as well as the final type that the function will return.
This PR includes:
- Parameter and return type hints for all functions (passed `MyPy` analysis)
- Explicit parameter assignment (i.e. `my_function(parameter=this, number=that)`). This makes it clear what parameter each  value is being mapped to when a function is called, and greatly improves the readability of our code base.
- A few minor tweaks to functions to improve bad logic, make naming/structure consistent, and fix loosely-typed functions
> Add parameter and return type hints to all functions

- easypost/requestor.py
- tests/cassettes/test_carrier_account_delete.yaml
- tests/cassettes/test_webhook_delete.yaml
When deleting a child user, our API endpoint will return HTTP 204 with an empty response body. This is a special case because HTTP 204 means the request is succeeded but doesn't have a response body, in our Python library it will throw an error because we never handle this corner, the root of the cause is `json.loads` in the `interpret_response` method because an error will be thrown when the response body is empty even thought the HTTP request is succeeded. See the screenshot below.
This PR checks if the HTTP Status response is 204, since the response body is empty the `json.loads()` will throw an error. Adding an if statement to handle the corner case.
Error stack:
> add conditional check if the http is 204 to prevent error being thrown.

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a template for future pull requests.
Link to the PR template view:https://github.com/EasyPost/easypost-python/blob/pr_template/.github/PULL_REQUEST_TEMPLATE.md
> add github pull request template.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Templates for bug reports and feature request templates
E2E internal
View templates: https://github.com/EasyPost/easypost-python/tree/bug_report/.github/ISSUE_TEMPLATE
> Added bug report and feature request templates

- easypost/address.py
- easypost/batch.py
- easypost/carrier_account.py
- easypost/order.py
- easypost/pickup.py
- easypost/report.py
- easypost/requestor.py
- easypost/resource.py
- easypost/scanform.py
- easypost/shipment.py
- easypost/tracker.py
- easypost/user.py
- easypost/webhook.py
We should not be sending query parameters in POST or PUT requests.
This PR:
- Adds safeguards against sending query parameters in POST or PUT requests
- Replaces method strings with RequestMethod enum to lock down request types
Re-ran all cassettes, all passed.
> Block query parameters in non-GET/DELETE requests

- CHANGELOG.md
- easypost/order.py
- easypost/pickup.py
- easypost/shipment.py
- easypost/util.py
- tests/cassettes/test_order_lowest_rate.yaml
- tests/cassettes/test_pickup_buy.yaml
- tests/cassettes/test_pickup_cancel.yaml
- tests/cassettes/test_pickup_create.yaml
- tests/cassettes/test_pickup_lowest_rate.yaml
- tests/cassettes/test_pickup_retrieve.yaml
- tests/cassettes/test_shipment_get_lowest_smartrate.yaml
- tests/cassettes/test_shipment_lowest_rate.yaml
- tests/cassettes/test_shipment_lowest_smartrate.yaml
- tests/conftest.py
- tests/test_order.py
- tests/test_pickup.py
- tests/test_shipment.py
- Adds `lowest_rate` functions to Orders and Pickups
- Adds a `Shipment.get_lowest_smartrate` function and a `shipment.lowest_smartrate()` function
> feat: adds lowest_rate to more objects

- tests/conftest.py
- tests/test_batch.py
- tests/test_referral.py
- tests/test_user.py
Cleans up the scrubbing logic for cassettes a bit to match that of the Ruby lib. Also properly dynamically waits for batch tests to finish if there is not yet a cassette.
> refactor: cassette scrubbing logic cleanup

- CHANGELOG.md
- easypost/address.py
Removes the unusable `carrier` param from `Address.verify()` along with the dead `message` conditional check that was missed in v7.0.0
NA
> chore: remove carrier verify param and dead address message code

- .gitattributes
Ignore cassette diffs locally (line 1) and collapse on GitHub (line 2) for easier review.
> chore: ignore cassette diffs via gitattributes

- CHANGELOG.md
- easypost/webhook.py
- tests/conftest.py
- tests/test_webhook.py
Adds a new function to validate if a webhook originated from EasyPost with the stored Webhook secret, if they do the function will return True, otherwise False.
- Adds a unit test to ensure this works by checking that the dummy webhook and secret match the expected hash for that same data.
> feat: adds validate webhook function

- easypost/address.py
- tests/cassettes/test_address_create_verify_array.yaml
- tests/cassettes/test_address_create_verify_strict.yaml
- tests/test_address.py
Allows for looser `verify` and `verify_strict` params because strings and bools are valid syntax (which is what we have documented). Also corrects the type hints for these. 
- Updates old tests to use booleans to match our docs
- Adds a new test to ensure array syntax still works. 
> fix: looser verify and verify_strict param type allowance

- .github/workflows/ci.yml
- Makefile
- README.md
- easypost/__init__.py
- easypost/beta/__init__.py
- setup.py
After weeks of checking, I see no usage for PyPy and deem it safe to remove the tests/plumbing for it. The library will continue to work with PyPy but we will no longer explicitly test for it. Doing so was slow and required some odd workarounds on CI to run them properly. This will reduce our testing complexity on CI while allowing us to maintain a single set of dependencies. If ever we really needed to be testing against this, we can always add it back in; however, I haven't heard of any complaints on the matter in the past.
Overhauled the dependencies to work as expected along with the build.
> chore: remove pypy tests and plumbing

- CHANGELOG.md
- easypost/shipment.py
- tests/test_shipment.py
Adds support to pass `end_shipper_id` in the `buy` function of a Shipment object.
Mocks the call to our API since we can't use VCR due to the fact that buying with an EndShipper ID requires a prod key which will buy real postage and we don't want to charge users.
> feat: adds end_shipper_id on the buy call of a Shipment

- CHANGELOG.md
- easypost/__init__.py
- easypost/referral.py
- tests/cassettes/test_beta_referral_add_credit_card.yaml
- tests/cassettes/test_beta_referral_user_all.yaml
- tests/cassettes/test_beta_referral_user_create.yaml
- tests/cassettes/test_beta_referral_user_update.yaml
- tests/test_beta_referral.py
Migrates the Partner White Label (Referral) function from beta to the general library namespace and deprecates the beta functions
- Adds new GA tests
- Retains beta tests until later removed
> feat: migrates partner white label (referral) to GA

- Makefile
- tests/conftest.py
This PR fixes the slow scrubbing operations due to an incorrectly placed for loop. By pulling the for loop outside of the recursive call, we aren't needlessly double, triple, etc running the foor loop inside of another foor loop down and down the rabbit hole. 
NOTE: The enforcement for coverage was dropped 1% since it was straddling the line and falls just beneath it on CI for some reason.
I tested a few cassettes getting re-recorded and ensured this worked as intended
> fix: slow scrubbing due to wrong for loop placement

- README.md
- tests/conftest.py
- tests/test_event.py
Adds a test utility that checks for expired cassettes on each run and throws errors if cassettes must be re-recorded due to old age to ensure the data is always up-to-date within a half year.
I set the days to ~40 and errors were thrown, setting it to 180 has the suite pass 
> feat: adds cassette expirations

- tests/conftest.py
Removes an unused enumeration for cassette scrubbing
> chore: remove unused enumeration in cassette scrubbing

- CHANGELOG.md
- easypost/error.py
- tests/test_error.py
Concatenates `error.message` if it incorrectly comes back from the API as a list
Adds a new unit test to ensure this works
> fix: concatenates error.message if it is a list

- .github/workflows/ci.yml
- CHANGELOG.md
- easypost/version.py
- setup.py
> chore: prepare v7.7.0 for release

- CHANGELOG.md
- easypost/beta/__init__.py
- easypost/beta/rate.py
- easypost/util.py
- tests/cassettes/test_beta_get_lowest_stateless_rate.yaml
- tests/cassettes/test_beta_retrieve_stateless_rates.yaml
- tests/cassettes/test_retrieve_stateless_rates.yaml
- tests/test_beta_rate.py
Adds new `retrieve_stateless_rates` function that takes in params like you would with shipment creation under the beta namespace.
Added a new test to ensure this works, inspected the cassette
> feat: add retrieve_stateless_rates function

- easypost/beta/__init__.py
- easypost/beta/carrier_metadata.py
- tests/cassettes/test_beta_retrieve_carrier_metadata.yaml
- tests/cassettes/test_beta_retrieve_carrier_metadata_with_filters.yaml
- tests/test_beta_carrier_metadata.py
Adds the new `/metadata` beta endpoint under `retrieve_carrier_metadata` allowing you to specify either a list of carriers or types or none to get it all.
Adds a test to retrieve all and another to use filters, inspected cassettes
> feat: add carrier metadata beta endpoint

- .github/workflows/ci.yml
- .gitignore
- Makefile
- setup.py
The previous implementation of coveralls used a Python package to generate `lcov` reports because `pytest-cov` previously didn't support it; however, just a month ago support was added. This PR removes the unneeded `coveralls` dependency and uses the same flow as our other repos to report which is much simpler
> simplify: coveralls reporting

- CHANGELOG.md
- easypost/payload.py
- setup.py
- Fixes a bug where `Payload` didn't inherit `EasyPostObject` which could throw errors when retrieving event payloads (closes #284)
NA, the error stemmed from this class just not having access to the parent classes due to missing inheritance.
> fix: payload inherits resource

- CHANGELOG.md
- easypost/easypost_client.py
- easypost/services/__init__.py
- easypost/services/carrier_metadata_service.py
- tests/cassettes/test_retrieve_carrier_metadata.yaml
- tests/cassettes/test_retrieve_carrier_metadata_with_filters.yaml
- tests/test_carrier_metadata.py
Moves carrier metadata to GA, adds tests, and deprecates the beta version.
Notable change from beta is the URL and the function name (retrieve instead of retrieve_carrier_metadata since it's already attached to the carrier metadata service now)
> feat: carrier metadata GA

- CHANGELOG.md
- Makefile
- README.md
- easypost/easypost_client.py
- easypost/hooks/__init__.py
- easypost/hooks/event_hook.py
- easypost/hooks/request_hook.py
- easypost/hooks/response_hook.py
- easypost/requestor.py
- tests/cassettes/test_request_hooks.yaml
- tests/cassettes/test_response_hooks.yaml
- tests/cassettes/test_unsubscribe_hooks.yaml
- tests/test_hook.py
- Adds new `RequestHook` and `ResponseHook` events. (un)subscribe to them with the new `subscribe_to_request_hook`, `subscribe_to_response_hook`, `unsubscribe_from_request_hook`, or `unsubscribe_from_response_hook` methods of an `EasyPostClient`
Adds a new set of tests that subscribe to the hooks and assert details only exposed via the hooks (not the traditional deserialized objects)
> feat: adds Request and Response Hooks

- setup.py
This pull request removes the unused dependency `typing-extensions` from the `setup.py` configuration file. The removal of this dependency is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.
The `typing-extensions` library was originally introduced to the project  in 35842786, however it  appears to be unused within the source code.
Removing this unused dependency  reduces the overall footprint of the application, mitigating potential security risks, and simplifying the dependency management process.
- Removed the `typing-extensions` dependency from `setup.py`.
- **Reduced Package Size**: The removal of this unused dependency will lead to a decrease in the overall size of the installed packages.
- **Simplified Dependency Tree**: …
> Remove Unused Dependency: typing-extesions

- CHANGELOG.md
- easypost/constant.py
- FedEx SmartPost carrier account registration should hit `/register` endpoint for creation
> [fix] FedEx SmartPost hits custom register endpoint

- CHANGELOG.md
- Makefile
- easypost/constant.py
- easypost/easypost_client.py
- easypost/services/__init__.py
- easypost/services/api_key_service.py
- easypost/services/user_service.py
- tests/cassettes/test_all_api_keys.yaml
- tests/cassettes/test_authenticated_user_api_keys.yaml
- tests/cassettes/test_child_user_api_keys.yaml
- tests/cassettes/test_demo_hooks.yaml
- tests/test_api_key.py
- tests/test_user.py
- Add dedicated API Key-related service, available via the `api_keys` property of a client
- NOTE: Please note the naming. The `api_key` property of a client is the currently-used API key string, while the `api_keys` property is the service for managing API keys.
- Migrate API key-related functions to API Keys service, deprecated in User service
- Migrate unit tests, re-record cassettes as needed
> [feat] Add dedicated API Keys service

- CHANGELOG.md
- easypost/constant.py
- setup.py
> chore: prepare v8.2.0 for release

- easypost/beta/user.py
- easypost/resource.py
- tests/cassettes/test_beta_user_get_next_page_collect_all.yaml
- tests/test_beta_user.py
The highlighted code (removed as part of this PR) was an invalid guard clause added at the root of our pagination functionality (and re-implemented for a recent beta child user pagination function in #300 ).
The highlighted code checked AFTER retrieving the "next page" of results if there were still more results to retrieve (the `has_more` boolean). If this was `False`, an error would be thrown alerting the user that there were no more pages to retrieve. However, in doing so, this would discard what we would then know is the last valid page of results, never returning them to the end-user. In effect, the end-user was never able to collect the very last page of results, because the function was always prematurely checking if yet another page exists afterwards. (The array length check also …
> [fix] Remove bad post-request guard clause in pagination functions

- CHANGELOG.md
- UPGRADE_GUIDE.md
- easypost/constant.py
- setup.py
> chore: prepare v9.0.0 for release

- setup.py
When we swapped from building our own packages to using the `build` packages, we forgot to remove `wheel` which is no longer needed. Additionally, `build` just hit v1 so it's a good time to upgrade. No breaking changes affect us
Ran `make build` and it worked as expected producing the stdist and wheel still
> chore: cleanup build deps

- CHANGELOG.md
- easypost/services/shipment_service.py
- easypost/util.py
Fixes the return type of the `regenerate_rates` function. Closes #317 
> fix regenerate rates type

- CHANGELOG.md
- easypost/beta/user.py
- easypost/requestor.py
- easypost/user.py
- tests/cassettes/test_user_all_children.yaml
- tests/cassettes/test_user_get_next_page.yaml
- tests/test_user.py
- Adds `all_children` function to the User class for retrieving paginated lists of children users, and deprecate the beta function
- Adds `get_next_page_of_children` function to the User class for retrieving next paginated lists of children users, and deprecate the beta function
Add unit tests for GA functions
> move all_children functions to GA

- CHANGELOG.md
- easypost/version.py
- setup.py
> prep release for v7.15.0

- pytest.ini
CI build is currently failing due to a doc generation tool introduced into our examples submodule a few months ago using pytest and has its own conftest.py file to execute, which causes build failing `_pytest.pathlib.ImportPathMismatchError:`
Add `pytest.ini` config file to tell pytest only look in the `tests` directory when running test suite.
> Fix CI build

- CHANGELOG.md
- easypost/services/billing_service.py
- tests/test_billing.py
- Use payment method object type as fallback when determining type for fund, delete functions
- Update, add unit test to confirm legacy (by ID prefix) and new (by object type) both work to determine payment method type
> [bug] Cannot determine payment method when funding/deleting

- easypost/services/tracker_service.py
- tests/cassettes/test_order_buy.yaml
- tests/cassettes/test_order_create.yaml
- tests/cassettes/test_order_get_rates.yaml
- tests/cassettes/test_order_lowest_rate.yaml
- tests/cassettes/test_order_retrieve.yaml
- tests/test_order.py
> chore: deprecate the create_list function

- CHANGELOG.md
- easypost/constant.py
- easypost/services/base_service.py
- easypost/services/carrier_account_service.py
- tests/cassettes/test_carrier_account_create_ups.yaml
- tests/cassettes/test_carrier_account_create_with_custom_workflow.yaml
- tests/cassettes/test_carrier_account_update.yaml
- tests/cassettes/test_carrier_account_update_ups.yaml
- tests/test_carrier_account.py
- Routes `UpsAccount`, `UpsMailInnovationsAccount`, and `UpsSurepostAccount` create/update requests to the new `/ups_oauth_registrations` endpoint
Adds new tests for each, updates previous custom workflow test to use FedEx instead of UPS
> feat: add new create_ups and update_ups functions

- Makefile
- tests/test_carrier_account.py
- Uses a new `init` make target to init the submodule instead of updating it on install to avoid CI blowing up.
- Fixes a variable in the recently added UPS test
> fix: init examples repo

- CHANGELOG.md
- easypost/easypost_client.py
- easypost/services/__init__.py
- easypost/services/shipment_service.py
- easypost/services/smartrate_service.py
- tests/cassettes/test_retrieve_estimated_delivery_date.yaml
- tests/cassettes/test_shipment_recommend_ship_date.yaml
- tests/cassettes/test_smartrate_estimate_delivery_date.yaml
- tests/cassettes/test_smartrate_recommend_ship_date.yaml
- tests/conftest.py
- tests/test_shipment.py
- tests/test_smartrate.py
- Adds new `shipment.recommend_ship_date`, `smartrate.recommend_ship_date`, and `smartrate.estimate_delivery_date` functions
Adds new tests that work similarly to how previous smartrate tests work
> feat: adds new recommend_ship_date and estimate_delivery_date functions

- easypost/services/shipment_service.py
Change desired_delivery_date to str instead of key-word args in Shipment.recommend_ship_date function
We should expect users to input a string and not a dict for the Shipment.recommend_ship_date function, this matches `retrieve_estimated_delivery_date` function
> Change desired_delivery_date to str instead of key-word args

- .github/workflows/ci.yml
- .github/workflows/release.yml
Now that we have an API Key saved to GitHub Actions for PYPI, we can use it to automate releasing this lib. Once a GitHub Release has been created (which automatically creates an accompanying tag), GitHub Actions will build and publish the library to PyPi.
I've used this workflow in ~40 other repos for the last ~3 years with 0 problems.
> feat: automated releasing via GitHub Actions

- CHANGELOG.md
- easypost/services/user_service.py
- tests/cassettes/test_user_children_get_next_page.yaml
- tests/test_user.py
fix get_next_page_of_children function for User service
Update test, remove an invalid test assertion that will always raise `KeyError`
> fix get_next_page_of_children function for User service

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Makefile
- setup.py
1. Tests against Python 3.13
1. Install types dynamically with mypy, this is more inline with what we do internally (removes explicitly defined ones from setup.py)
1. Removes `twine` since we now use GitHub Actions to release, that package is not needed since it's already contained in the action we use
> chore: test on python 3.13

- CHANGELOG.md
- easypost/services/webhook_service.py
- tests/cassettes/test_webhook_create.yaml
- tests/cassettes/test_webhook_update.yaml
- tests/conftest.py
- tests/test_webhook.py
- Fixes wrapping of payload for update webhook function
- Beefs up webhook create/update tests by testing secret and custom_headers
> test: additional params in webhook create/update calls

- tests/cassettes/test_error_alternative_format.yaml
- tests/test_address.py
- tests/test_error.py
Adds tests for alternative format errors and address verification errors.
> test: alternative error format

- tests/conftest.py
- tests/test_beta_referral_customer.py
- tests/test_billing.py
- tests/test_referral_customer.py
Uses new billing fixtures in tests
> chore: use new billing fixtures

- CHANGELOG.md
- UPGRADE_GUIDE.md
- easypost/constant.py
- setup.py
> chore: prep v10.0.0 for release

- CHANGELOG.md
- easypost/constant.py
- easypost/services/base_service.py
- easypost/services/carrier_account_service.py
- setup.py
- tests/cassettes/test_carrier_account_create_ups.yaml
- tests/cassettes/test_carrier_account_update_ups.yaml
- tests/test_billing.py
> fix: endpoint used for UPS create/update
