EasyPost/easypost-python

easypost/__init__.py

Add to_json method to get plain json from an EasyPostObject.

add to_json method

---

.gitignore
easypost/__init__.py
tests/test_batch.py
tests/test_carrier_type.py

#67 fixes api_key credentials issue.

Fixed api_key bug.

---

tests/test_report.py

Fixes #80
Also, makes this test run again, which it hasn't done since... 2017...

remove weird double-indentation from test_report.py

---

easypost/__init__.py

Removed the unpaginated endpoints for customsInfo, customsItems, Pickups, and Orders as we are doing on other CLs.

Removed unpaginated all endpoints for customs, pickups, and orders

---

easypost/__init__.py
examples/event.py

Added event retrieval functionality and example.

Added event retrieval and example

---

easypost/__init__.py

It has never in the life of the company been possible to list parcels.
Fixes internal issue T28563.

parcels do not support listing and never have

---

tests/cassettes/test_address_creation_with_verify.yaml
tests/test_address.py

Summary: AVS does not correct "streat" to "st" and was appending "streat" to output
Differential Revision: https://phab.easypo.net/D28024

"fixed" test by accepting minor change in AVS behavior

---

easypost/__init__.py

This removes extraneous encoder code (without losing important functionality of course). A few things have been renamed for clarity, and some class methods (encoding URL params) that I felt had no relation to the class have been moved to functions as well.

Slim down the query encoder

---

tests/cassettes/test_tracker_create_list.yaml
tests/test_tracker.py

Adds missing test for tracker `create_list` method.

test: adds missing test for tracker create_list

---

CHANGELOG.md
easypost/__init__.py
examples/unicode.py
tests/test_address.py

Add the `update_brand()` method to the User object.
End-to-end tested this successfully. Did not record a cassette and check it in because it would expose my user details.

feat: add the update_brand method to the user object

---

CHANGELOG.md
easypost/__init__.py
tests/cassettes/test_retrieve_me.yaml
tests/test_user.py

Python library is currently missing the retrieve_me function. This is the same as retrieving a user without specifying an ID, but some libs have a specific function for this. Unifying this to make our libraries more consistent.

Retrieve me

---

easypost/report.py
tests/cassettes/test_report_create_with_additional_columns.yaml
tests/cassettes/test_report_create_with_columns.yaml

This PR moves the columns and additional_columns from URL query to request body because a long query URL can be rejected or silently truncated.
E2E test:

move columns and additional_columns from query string to request body.

---

CHANGELOG.md
easypost/address.py
tests/cassettes/test_address_create_and_verify.yaml
tests/cassettes/test_address_create_verify.yaml
tests/cassettes/test_address_create_verify_strict.yaml
tests/conftest.py
tests/test_address.py

- Removes dead message conditional check in Address create and verify
- Updates a few address assertions to match internal API changes

remove message conditional check in address create and verify.

---

CHANGELOG.md
Makefile
README.md
UPGRADE_GUIDE.md
easypost/version.py
setup.py

Prepares v7.0.0 for release
- Updates versions
- Updates CHANGELOG
- Adds UPGRADE_GUIDE
- Adds releasing dependencies in preparation to publish
- Updates Makefile to make publishing easier
Ran `make clean install install-release build` multiple times and ensured that the `sdist` and `bdist` were generated to `dist` properly.

chore: prepare v7.0.0 for release

---

.github/PULL_REQUEST_TEMPLATE.md

Swap the order of the pull request template.
N/A

swap the order of PR template.:

---

CHANGELOG.md
easypost/__init__.py
easypost/beta/__init__.py
easypost/beta/referral.py
easypost/requestor.py
tests/cassettes/test_referral_user_all.yaml
tests/cassettes/test_referral_user_update.yaml
tests/test_referral.py

Add beta functions for White Label API
Create a new folder called `beta` with Referral class
`Referral` class has these new function:  `CreateReferral()`, `UpdateReferral()`, `ListReferral()`, and `AddCreditCard()`
Since there are some sensitive info, E2E test for `CreateReferral` in Partner class and `AddCreditCard` in Referral class

add white label API functions.

---

CHANGELOG.md
easypost/version.py
setup.py

Prepares v7.1.0 for release
NA

chore: prepare v7.1.0 for release

---

CHANGELOG.md
easypost/version.py
setup.py

Fixes package/module discovery in `setup.py` by allowing setuptools to dynamically discover packages instead of requiring us to list them all - ignores tests and examples in the final product.
Also prepares v7.1.1 for release.
Closes #189 

fix: package discovery

---

easypost/beta/referral.py
easypost/requestor.py
easypost/user.py

There is some old logic surrounding what functions require an API key and which don't (they all do at present). This PR cleans up that logic to avoid confusion and be more precise.
- Tests pass

fix: require an API key for child user creation

---

CHANGELOG.md
easypost/__init__.py
easypost/credit_card.py
easypost/payment_method.py
tests/cassettes/test_payment_method_all.yaml
tests/test_credit_card.py
tests/test_payment_method.py

Adds `PaymentMethod.all()`, `CreditCard.fund()`, and `CreditCard.delete()` functions

feat: adds user billing functions

---

easypost/requestor.py
easypost/resource.py
easypost/user.py
easypost/webhook.py
tests/cassettes/test_carrier_account_update.yaml
tests/cassettes/test_user_update.yaml
tests/cassettes/test_user_update_brand.yaml
tests/cassettes/test_webhook_update.yaml

changed the HTTP Put method for the PATCH method in the brand, carrier account, user, and webhook classes.

swap to use HTTP PATCH method

---

tests/test_credit_card.py

changed CreditCardFund test from 20 to 2000

Update CreditCardFund test

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepares v6.0.1 for release

---

tests/cassettes/test_referral_user_all.yaml
tests/test_referral.py

changed the referral test all method to account for new referral_customers keys.
updated cassettes. 

updated referral test

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepares v7.2.0 for release

---

CHANGELOG.md
easypost/shipment.py
tests/cassettes/test_generate_form.yaml
tests/conftest.py
tests/test_shipment.py

Adds `generate_form` function to the Shipment object
Added a new test and passed

Adds generate_form function to the Shipment object

---

easypost/shipment.py

lowercase `delivery_accuracy` to avoid any uppercase that can cause a mismatch in the percentile.
N/A

lowercase delivery accuracy

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepare v7.3.0 for release

---

tests/test_order.py
tests/test_pickup.py

There were a couple of silently succeeding error test assertions that are patched here. Now if they ever fail we'll know (whereas before they would have passed incorrectly).

fix: silently succeeding error message assertions

---

.gitignore

chore: ignore .env files

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepares v7.4.0 for release

---

.github/workflows/ci.yml
Makefile
README.md

Unifies the Makefile and adds a `release` target.

chore: unifies Makefile and adds release target

---

Makefile
easypost/address.py
easypost/billing.py
easypost/event.py
easypost/report.py
easypost/scanform.py
easypost/shipment.py
easypost/user.py

Removes redundant inheritance of objects that provide a local method with the same type. This should reduce complexity and confusion and was not necessary.
- Ran tests

fix: removes redundant inheritance for methods that exist locally

---

tests/conftest.py

Uses the new event-body JSON file fixture
N/A

Uses the new event-body JSON file fixture

---

CHANGELOG.md
easypost/__init__.py
easypost/easypost_object.py
easypost/endshipper.py
tests/cassettes/test_endshipper_all.yaml
tests/cassettes/test_endshipper_create.yaml
tests/cassettes/test_endshipper_retrieve.yaml
tests/cassettes/test_endshipper_update.yaml
tests/test_endshipper.py

Adds the new `EndShipper` beta class with create, retrieve, all, and update functions. This is the fully-qualified address object that the USPS will start requiring shortly.
Add unit tests and pass them

Add EndShipper

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepares v7.5.0 for release

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepares v7.6.0 for release

---

tests/cassettes/test_endshipper_all.yaml
tests/cassettes/test_endshipper_create.yaml
tests/cassettes/test_endshipper_retrieve.yaml
tests/cassettes/test_endshipper_update.yaml
tests/cassettes/test_shipment_buy_with_end_shipper_id.yaml
tests/test_endshipper.py
tests/test_shipment.py

Switches EndShipper tests to test mode now that it's supported

tests: switch EndShipper tests to test mode

---

.github/workflows/ci.yml

Enables workflow dispatch on CI

chore: workflow_dispatch on CI

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepares v7.6.1 for release

---

.github/workflows/ci.yml

chore: add Python 3.11 to CI

---

.github/workflows/ci.yml
README.md
setup.py

Adds coveralls dependency and step to CI to report coverage to coveralls

feat: add coveralls

---

CHANGELOG.md
easypost/carrier_account.py
easypost/error.py
tests/cassettes/test_carrier_account_register.yaml
tests/test_carrier_account.py

Adds custom registration function for carriers with custom flows such as FedEx or UPS
Adds a test to ensure the request went to the right place

feat: adds register function to CarrierAccount for custom registration carriers

---

tests/cassettes/test_refund_create.yaml
tests/test_refund.py

Fixes a test that should be sending the tracking codes as a list.

fix: refund tracking codes test

---

CHANGELOG.md
easypost/pickup.py
tests/cassettes/test_pickup_all.yaml
tests/test_pickup.py

Adds a retrieve all pickups function now that this endpoint is paginated.
Adds new test to ensure this worked.

feat: add retrieve all pickups

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepare v7.9.0 for release

---

README.md

docs: adds lib docs link to README

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepare v7.10.0 for release

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepare v7.11.0 for release

---

CHANGELOG.md
easypost/version.py
setup.py

chore: prepare v7.12.0 for release

---

CHANGELOG.md
easypost/shipment.py
tests/cassettes/test_retrieve_estimated_delivery_date.yaml
tests/test_shipment.py

- Adds `retrieve_estimated_delivery_date` function to the Shipment class
Adds a unit test to ensure the correct keys are in the response

feat: adds retrieve_estimated_delivery_date function

---

.github/workflows/ci.yml
easypost/beta/referral.py
easypost/easypost_object.py
easypost/order.py
easypost/pickup.py
easypost/referral.py
easypost/report.py
easypost/requestor.py
easypost/shipment.py
easypost/util.py
setup.py

- Drops Python 3.6
- Modernizes dependencies
- Fixes new mypy errors due to upgrade

chore: modernize deps, drop Python 3.6

---

easypost/beta/referral.py
easypost/billing.py
easypost/referral.py
tests/test_beta_referral.py
tests/test_billing.py

Renames `primary_or_secondary` param to `priority`

fix: rename primary_or_secondary to priority

---

easypost/billing.py
easypost/referral_customer.py
easypost/tracker.py
tests/test_billing.py
tests/test_referral_customer.py
tests/test_tracker.py

For API calls that don't return a body, we previously returned `True`, to better match the API response, we will now return `None` for those few functions that don't have a return type

chore: return none instead of true

---

CHANGELOG.md
README.md
UPGRADE_GUIDE.md
easypost/constant.py
easypost/services/billing_service.py
setup.py
tests/test_billing.py

- Adds the v8 upgrade guide
- Bumps version (date may change based on when we release)
Built the binaries locally to ensure after all the changes that building still works.

docs: adds v8 upgrade guide

---

CHANGELOG.md
UPGRADE_GUIDE.md

chore: update release date of v8

---

.github/workflows/ci.yml
Makefile
README.md

To match internal decisions, we're making `lint` the target that does all the things

fix: lint target

---

CHANGELOG.md
easypost/errors/api/__init__.py
easypost/errors/api/bad_request_error.py
easypost/requestor.py

- Maps 400 status codes to new `BadRequestError` class

feat: maps 400 status codes to new BadRequestError class

---

CHANGELOG.md
easypost/constant.py
setup.py

[chore] Prep release

---

CHANGELOG.md
setup.py

- Bump version number, update changelog
- N/A

[chore] Prep v7.14.0 release

---

.github/workflows/ci.yml

tests: check we build on python 3.12

---

CHANGELOG.md
easypost/version.py
setup.py

- Bump version, update changelog
- N/A

[chore] Prep for v7.14.1 release

---

easypost/services/base_service.py
tests/test_base_service.py

See #303 for details.
- Add unit test for base pagination flow verifying that all pages of results are returned and accessible to end-users (using scanforms as an example)

[fix] Fix pagination bug

---

CHANGELOG.md
easypost/constant.py
setup.py

- Bump version, update CHANGELOG
- N/A

- Prep for v8.2.1 release

---

easypost/services/report_service.py

fix: report variable name

---

easypost/constant.py
setup.py

chore: prepare v9.0.1 for release

---

CHANGELOG.md
Makefile
easypost/services/user_service.py
tests/cassettes/test_user_all_children.yaml
tests/cassettes/test_user_children_get_next_page.yaml
tests/test_user.py

- Adds `all_children` function to the User service for retrieving paginated lists of children users
- Adds `get_next_page_of_children` function to the User service for retrieving next paginated lists of children
Add unit tests

add all_chilren and get_next_page_of_children functions

---

tests/cassettes/test_address_create_verify.yaml
tests/cassettes/test_address_create_verify_array.yaml
tests/test_address.py

See https://github.com/EasyPost/easypost-csharp/pull/540 for more details.
- Update examples submodule for new "incorrect address" fixture
- Improve address verification unit tests to better test target functionality
- Update unit tests, re-record cassettes as needed

[chore] Improve address verification unit tests

---

CHANGELOG.md
easypost/constant.py
setup.py

- Bump version number
- Update changelog

[chore] Prep for v9.1.0 release

---

CHANGELOG.md
easypost/version.py
setup.py

- Bump version number
- Update changelog (disavow v7.15.0)

[chore] Prep for v7.15.1 release

---

CHANGELOG.md
easypost/constant.py
setup.py

prep release v9.2.0

---

README.md
setup.py

fix: docs link

---

easypost/easypost_client.py
easypost/services/smartrate_service.py
tests/test_smartrate.py

fix: smart_rate service naming

---

CHANGELOG.md
easypost/constant.py
setup.py

chore: prepare v9.3.0 for release

---

CHANGELOG.md
easypost/constant.py
setup.py

- Bump version number
- Update CHANGELOG

[chore] Prep for v9.4.0 release

---

setup.py

upgrade twine for release

---

CHANGELOG.md
easypost/constant.py
setup.py

chore: prepare v9.4.1 for release

---

CHANGELOG.md
easypost/constant.py
easypost/services/tracker_service.py
setup.py

`tracking_codes` is the preferred param to use for filtering tracking codes on the index endpoint - added here

feat: add tracking_codes as param for all on TrackerService

---

easypost/services/luma_service.py
tests/test_luma.py

fix: luma response

---

CHANGELOG.md
easypost/constant.py
setup.py

chore: prep v10.1.0 for release
